title: Tony Wu
description: Just a student with an interest in cyber security and software development.
baseurl: "/"
url: "https://qwutony@github.io"
twitter_username: Katsurasec
github_username:  qwutony

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - Gemfile
#   - Gemfile.lock